name: Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration=production --output-path=dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Mumbai Region

      - name: Upload build to S3
        run: aws s3 sync dist s3://awss3forproject1/ --delete

      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r dist/* deploy/
          zip -r deploy.zip deploy

      - name: Upload deployment package to S3
        run: aws s3 cp deploy.zip s3://awss3forproject1/deploy.zip
