name: Build and Upload to S3

on:
  push:
    branches:
      - main  # Change if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Required for Angular CLI

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration=production --output-path=dist

      - name: Create Deployment ZIP
        run: |
          mkdir -p deployment-package
          cp -r dist deployment-package/
          cp appspec.yml deployment-package/
          cp -r scripts/ deployment-package/  # Ensure any necessary scripts are included
          cd deployment-package && zip -r ../deployment.zip . && cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Mumbai region

      - name: Upload ZIP to S3
        run: |
          aws s3 cp deployment.zip s3://awss3forproject1/deployment.zip
