name: Build Angular Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --configuration=production --output-path=dist

    - name: Verify build output
      run: ls -la dist  # Check if build files exist
